<!DOCTYPE html>
<html lang="de">

<head>
  <?php include('websiteNEWASSETS/includes/head.php'); ?>
  <style>
    .h_dark {
      background: #273B5D;
    }
  </style>
</head>

<body>
  <div class="body_wrapper">

            <?php include('websiteNEWASSETS/includes/header.php'); ?>

    <!--<section class="breadcrumb_area" style="background-image: url('img/Img-05.jpg'); background-position:  center center; background-repeat: no-repeat; background-size: cover;">
            <img class="breadcrumb_shap" src="websiteNEWASSETS/img/breadcrumb/banner_bg.png" alt="">
            <div class="container">
                <div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">Senior ui/ux designer</h1>
                    <p class="f_400 w_color f_size_16 l_height26">Why I say old chap that is spiffing off his nut arse pear shaped plastered<br> Jeffrey bodge barney some dodgy.!!</p>
                </div>
            </div>
        </section>-->
    <section class="job_details_area sec_pad">
      <div class="container">
        <div class="details_content">
          <div class="sec_title mb_70">
            <br><br>
            <h2>Data protection</h2>
            <!--<h3 class="f_p f_size_22 f_500 t_color3 mb_20">Angaben gemäß § 5 TMG</h3>-->
          </div>

          <p class="f_400 f_size_15">


          With this data protection declaration, we would like to inform you in accordance with Art. 13 and 14 of the General Data Protection Regulation (GDPR) how our company processes personal data during the use of the online offers (hereinafter also "website") and other services and to inform you about your rights . We process your personal data in compliance with the GDPR and all other applicable data protection regulations. This data protection declaration uses the terms of the GDPR. The terms used, such as "user" are to be understood as gender-neutral. 
<br><br>
<b>1. Responsible and data protection</b>
<br>officer DokuMe UG (limited liability)<br>
Fritz-Figge-Str. 13, 50823 Köln<br>
E-Mail: <a href="info@dokume.in">info@dokume.in</a>
<br><br>
Kontaktdaten der Datenschutzbeauftragten: <a href="mailto:privacy@dokume.in">privacy@dokume.in</a><br><br>

<b>2. Categories and origin of the data we process</b>
<br>
We process personal data from visitors and users of our online offer (hereinafter we refer to the persons concerned collectively as "users") if you communicate via other channels contact us and also if third parties make this data available to us.
<br><br>
<u>2.1. Data generated by visiting our website</u>
<br>
When you visit our website, it is technically necessary for data to be transmitted to our web server via your internet browser. The following data is recorded in a server log file during an ongoing connection for communication between your internet browser and our web server:
<ul>
<li>Visited domain
<li>Date and time of the request</li>
<li>Page from which the file was requested</li>
<li>Access status (file transferred, file not found, etc.)</li>
<li>Web browser and operating system used</li>
<li>IP address of the requesting computer (possibly also Internet provider)</li>
<li>Amount of data transferred</li>
</ul>
In principle, this data is not merged with other data sources.
<br><br>
<u>2.2. Other processed data</u>
<br>
Your data is collected on the one hand by the fact that you communicate it to us. This can be z. B. be data that you enter in a contact form or data you provide to create a customer account.
<br><br>
Apart from the data generated by visiting our website, we also process inventory data (e.g. names, addresses), contact data (e.g. e-mail, telephone numbers), content data (e.g. text entries, photographs) if you make them available to us , videos), usage data (e.g. registration status, access times), applicant data (e.g. CVs, job references).
<br><br>
<u>2.3. Data we receive from external sources</u>
<br>
Third parties (e.g. companies, organizations, associations to which you belong) can create a user account for you via our online offers. A confirmation message will be sent to the specified email address. If the account created is not activated within 30 days by a link in the confirmation message, it will be automatically deleted. The following data is usually stored by third parties to create an account: Inventory data (e.g. names, addresses), contact data (e.g. e-mail, telephone numbers), content data (e.g. text entries, photographs, videos).
<br><br>
<b>3. Purposes and legal basis of processing</b>
<br>
We process your data for one or more of the following purposes:
<br><br>
<ul>
  <li>for the <b>security and presentation of our website</b> (log files),</li>
  <li>for the <b>contact</b> you wish to make,,</li>
  <li>to create and use <b>user accounts</b>,</li>
  <li>to process or initiate <b>contracts</b> with you,</li>
  <li>for <b>promotional purposes</b>, and/or</li>
  <li>for <b>statistical evaluations and analysis</b> of our services;</li>
</ul>

Your data is processed in accordance with the following legal bases: your consent in accordance with Article 6 (1) (a) GDPR or, if applicable, Article 9 (2) (a) GDPR, for the execution of a contract with you in accordance with Article 6 1 lit. b GDPR or, if applicable, Art. 9 (2) lit. b GDPR, to fulfill legal obligations pursuant to Art. 6 (1) lit. c GDPR or for a legitimate interest pursuant to Art GDPR.
<br><br>
In detail, we use your data for one or more of the following purposes and with the corresponding legal bases:
<br><br>
<u>3.1. Security and presentation of our website</u>
<br>
Every time our website is accessed, usage data is transmitted by the respective Internet browser and stored in log files, the so-called server log files. The data records saved in this way are listed under point 2.1. These log file data records may be evaluated in order to protect our website against attacks, to find and correct errors and to control server utilization. This is also our legitimate interest according to Art. 6 Para. 1 lit. f GDPR. We reserve the right to check the log data if there is a justified suspicion of illegal use based on specific indications.
<br><br>
Cookies and other technologies may be required for the complete and correct display of our website. Unless otherwise specified, the complete and correct presentation is a legitimate interest on our part in this data processing in accordance with Article 6 (1) (f) GDPR.
<br><br>
<u>3.2. Establishing contact</u>
<br>
If you contact us (e.g. via the contact form), we store your details for processing the inquiry and in the event that follow-up questions arise.
<br><br>
If you wish to be contacted, for example because you send us an e-mail message or write to us via a contact form, the legal basis is Art. 6 (1) lit. f GDPR. We have a legitimate interest in fully processing your contact. Since you are contacting us, we assume that you have no interests that prevent us from processing your request. If contact is aimed at concluding a contract or fulfilling a contract, the legal basis for processing is Art. 6 (1) (b) GDPR. If consent has been given, the legal basis for processing to establish contact is Art. 6 (1) (a) GDPR or, if applicable, Art. 9 (2) (a) GDPR.
<br><br>
<u>3.3. customer accounts</u>
<br>
You can register for certain services offered on our website and thereby create a customer account or user profile. We process your personal data in order to be able to provide you with our online services. For the new registration, we collect, among other things, master data (e.g. name, address), communication data (e.g. e-mail address) and access data (e.g. user name, password).
<br><br>
The processing of the data from your customer account takes place on the basis of the contractual relationship (or initiation) that you enter into with us, insofar as the data is required for the fulfillment (or conclusion) of the contract. The basis of this data processing is Art. 6 Para. 1 lit. b GDPR. For other purposes, such as the use of specific apps and functionalities within our online platform, we process your personal data if we have your consent (Art. 6 Para. 1 lit. a DSGVO or Art. 9 Para. 2 lit. a GDPR) is available. We also inform you which personal data can be processed by an app or functionality.
<br><br>
<u>3.4. contracts</u>
<br>
We process certain personal data if you conclude a contract with us or during the initiation of a contractual relationship and insofar as the correspondingly processed data is necessary for the execution or conclusion of the respective contract or the initiation of the contractual relationship. In this case, the basis for data processing is Art. 6 (1) (b) GDPR.
<br><br>
In the case of applications that do not lead to a contractual relationship, we have a legitimate interest in keeping track of the application data for a limited period of time in accordance with Article 6 (1) (f) GDPR in order to assert our legal claims or to defend ourselves against lawsuits.
<br><br>
<u>3.5. promotional purposes</u>
<br>
We process your personal data for advertising purposes if we have given your consent in accordance with Article 6 (1) (a) GDPR. This is the case, for example, if you subscribe to our newsletter (via a double opt-in procedure). A success measurement of the newsletter takes place. The data you have stored with us for the purpose of subscribing to the newsletter will be stored by us with our newsletter dispatch provider until you unsubscribe from the newsletter and will be deleted from the newsletter distribution list after you have canceled the newsletter. Data stored by us for other purposes remain unaffected. After you have been removed from the newsletter distribution list, your e-mail address may be stored in a blacklist by us or the newsletter dispatch provider in order to prevent future mailings. The data from the blacklist is only used for this purpose and is not merged with other data. This serves both your interest and our interest in complying with the legal requirements when sending newsletters (legitimate interest within the meaning of Art. 6 Para. 1 lit. f GDPR). Storage in the blacklist is not limited in time. You can object to the storage if your interests outweigh our legitimate interests. You can revoke your consent to the storage and use of your data for sending the newsletter at any time. The revocation can be made via a link in the newsletter. This serves both your interest and our interest in complying with the legal requirements when sending newsletters (legitimate interest within the meaning of Art. 6 Para. 1 lit. f GDPR). Storage in the blacklist is not limited in time. You can object to the storage if your interests outweigh our legitimate interests. You can revoke your consent to the storage and use of your data for sending the newsletter at any time. The revocation can be made via a link in the newsletter. This serves both your interest and our interest in complying with the legal requirements when sending newsletters (legitimate interest within the meaning of Art. 6 Para. 1 lit. f GDPR). Storage in the blacklist is not limited in time. You can object to the storage if your interests outweigh our legitimate interests. You can revoke your consent to the storage and use of your data for sending the newsletter at any time. The revocation can be made via a link in the newsletter. You can revoke your consent to the storage and use of your data for sending the newsletter at any time. The revocation can be made via a link in the newsletter. You can revoke your consent to the storage and use of your data for sending the newsletter at any time. The revocation can be made via a link in the newsletter.
<br><br>
In a few cases, the processing of your personal data can take place due to our legitimate interest (Art. 6 Para. 1 lit. f) GDPR) in the promotion of our products, for example if you are an existing customer of our company (see also Recital 47 GDPR and § 7 UWG).
<br><br>
<u>3.6. Statistical evaluation and analysis of our services</u>
<br>
We process your personal data for the statistical evaluation and analysis of our website (e.g. via cookies and other technologies) and our services if we have given your consent in accordance with Article 6 (1) (a) GDPR. Due to the need for bookkeeping, there could be an indirect statistical evaluation of your personal data due to a legal obligation (Art. 6 Para. 1 lit. c GDPR). In addition, your data could be processed for the purpose of statistically evaluating the key figures of our economic activity. According to Art. 6 Para. 1 lit. f GDPR, this represents a legitimate interest of our company, as it enables us to plan financially and allocate resources economically.
<br><br>
<b>4. Legitimate interests</b>
<br>
Unless otherwise stated in this data protection declaration and if we base the processing of your personal data on legitimate interests in accordance with Article 6 Paragraph 1 lit Evaluation of our offer and the processing of incoming inquiries.
<br><br>
<b>5. Recipients or categories of recipients of the personal data</b>
<br>
When processing your data, we work with service providers who have access to your data. Possible recipients of your personal data are: (i) software companies that enable us to provide our services, help improve them and/or serve us for marketing purposes (e.g. to administer newsletters); (ii) public bodies and administrations, insofar as we are legally obliged to do so; (iii) payment service providers; (iv) hosting provider; (v) Service companies, such as accountants or accountants.
<br><br>
For the purpose of fulfilling the contract, we can also transfer your personal data to anyone to whom we assign rights resulting from the contractual relationship with you.
<br><br>
Some of the recipients of the personal data that we process on our website and for our services are:
<br><br>
<i>Apple & Firebase Cloud Messaging</i>
<br>
We use Apple and Firebase Cloud Messaging for our services. Personal data can be passed on here. We use these services to send push notifications to our customers.
<br><br>
<a href="https://policies.google.com/privacy?hl=de" target="_blank">https://policies.google.com/privacy?hl=de</a><br>
<a href="https://www.apple.com/legal/privacy/en-ww/" target="_blank">https://www.apple.com/legal/privacy/en-ww/</a>
<br><br>
<i>Coconut</i>
<br>
We offer our customers services from Coconut. Personal data can be passed on here. The services are used to edit videos, eg to make them smaller.
<br><br>
<a href="https://coconut.co/tos" target="_blank">https://coconut.co/tos</a>
<br><br>
Google Ireland Limited
<br>
We embed services from Google on our website and in our services to (i) embed fonts. Personal data can be passed on to Google. We use the services mentioned to (i) offer a complete and attractive website (Google Fonts).
<br><br>
<a href="https://policies.google.com/privacy?hl=de" target="_blank">https://policies.google.com/privacy?hl=de</a>
<br><br>
<i>gridscale GmbH</i>
<br>
We use the services of gridscale GmbH to host our website and online offers. Personal data can be passed on here. We use the services mentioned to be able to offer a website and platform.
<br><br>
<a href="https://gridscale.io/en/datenschutzerklaerung/" target="_blank">https://gridscale.io/en/datenschutzerklaerung/</a>
<br><br>
<i>Microsoft Azure</i>
<br>
We use blob storage to offer our customers document storage. Your personal data will be transmitted to Microsoft. We use these services to improve our administrative and collaboration processes and to provide a functional website.
<br><br>
<a href="https://privacy.microsoft.com/en-us/PrivacyStatement" target="_blank">https://privacy.microsoft.com/en-us/PrivacyStatement</a>
<br><br>
<i>Mailjet</i>
<br>
We use Mailjet as our email delivery provider. After registration, your contact details will be forwarded to our e-mail dispatch provider in order to contact you in connection with your user account or, if applicable, the newsletter.
<br><br>
<a href="https://www.mailjet.de/privacy-policy/" target="_blank">https://www.mailjet.de/privacy-policy/</a>
<br><br>
<b>6. Transmission to third countries</b>
<br>
Data is transferred to third countries outside the European Union or the European Economic Area. Information we collect from you may be processed in the United States or other third countries. Some third countries, such as the United States, have not currently received an adequacy decision under Article 45 of the GDPR from the European Union, which means your data may not receive the same level of protection there as under the GDPR.
<br><br>
International data transfers usually take place on the basis of statutory contractual or other regulations intended to ensure adequate protection of your data and which you can inspect on request. In doing so, we rely on the provisions set out in Article 49 of the GDPR or, where applicable, on guarantees under Article 46 of the GDPR. We and our processors aim to use appropriate safeguards to protect the privacy and security of your personal information. Therefore, we only process your personal data in accordance with the practices described in our privacy policy.
<br><br>
<b>7. Duration of storage</b>
<br>
We only store your personal data for as long as is necessary to achieve the processing purpose. We store your data if you have consented to the processing, at most until you revoke your consent, if we need the data to execute a contract, at most for as long as the contractual relationship with you exists (including the defense against and enforcement of legitimate claims within the limitation periods), if we use the data on the basis of a legitimate interest, at most as long as your interest in deletion or anonymization does not prevail.
<br><br>
Storage can also take place if this has been provided for by the European or national legislator in EU regulations, laws or other regulations to which the person responsible is subject (including tax law, commercial law, combating money laundering). In order not to violate legal regulations or lose the opportunity to assert a claim or to defend ourselves against one, we reserve the right to delete the data only after the last retention period that legitimizes the data storage has expired.
<br><br>
We store applicant documents for a period of six months if the application does not lead to an employment relationship and no further storage has been agreed. This period results from possible lawsuits against the person responsible under the General Equal Treatment Act (AGG).
<br><br>
To send our newsletter, we store your email address until you unsubscribe from the newsletter.
<br><br>
<b>8. Your rights and revocation of your consent</b>
<br>
As the person affected by the data processing, you may have the right under the applicable data protection law to:
<ul>
  <li>Information, according to Art. 15 GDPR,</li>
  <li>Correction, according to Art. 16 GDPR,</li>
  <li>Data deletion ("right to be forgotten"), according to Art. 17 GDPR,</li>
  <li>Restriction of processing according to Art. 18 GDPR,</li>
  <li>Data portability, according to Art. 20 GDPR and/or</li>
  <li>Objection to the processing, according to Art. 21 GDPR.</li>
</ul>

<i>Information on the right to object in accordance with Article 21 (4) GDPR</i>
<br>
You have the right, for reasons arising from your particular situation, to object at any time to the processing of personal data relating to you, which is based on Article 6 (1) e) or f ) GDPR to file an objection; this also applies to profiling based on these provisions. We no longer process personal data unless we can demonstrate compelling legitimate grounds for processing that outweigh your interests, rights and freedoms, or the processing serves to assert, exercise or defend legal claims.
<br><br>
If your personal data is processed in order to operate direct advertising, you have the right to object at any time to the processing of your personal data for the purpose of such advertising; this also applies to profiling insofar as it is associated with such direct advertising.
<br><br>
<i>Withdrawal of consent</i>
<br>
You also have the right to withdraw consent to the processing of personal data at any time. The revocation of the consent does not affect the legality of the processing carried out on the basis of the consent up to the point of revocation.
<br><br>
<b>9. Right to lodge a complaint with a supervisory authority</b>
<br>
According to Art. 77 GDPR, you have the right to lodge a complaint with a supervisory authority, in particular in the member state of your place of residence, your place of work or the place of the alleged infringement, if you believe that the processing of your personal data violates the GDPR or other data protection regulations.
<br><br>
<b>10. Necessity to provide personal data</b>
<br>
We clarify that the provision of personal data is partly required by law (e.g. tax regulations) or can also result from contractual regulations (e.g. information on the contractual partner). Sometimes it may therefore be necessary for an affected person to provide us with personal data, which we subsequently process. For example, the data subject is obliged to provide us with personal data if our company concludes a contract with them. Failure to provide the personal data would mean that the contract with the data subject could not be concluded. Before personal data is provided, the person concerned can contact us. We clarify on a case-by-case basis
<br><br>
With regard to our website, it is generally the case that the personal data required for use is marked as such. If this necessary personal data is not provided, this may result in certain functions not being available or our services and services not being able to be used.
<br><br>
<b>11. Automated decision</b>
<br>
-making We do not use automated decision-making mechanisms — including profiling — that have legal effects on the data subject or significantly affect them in a similar way.
<br><br>
<b>12. Data Security</b>
<br>
We make every effort to ensure the security of your data within the framework of the applicable data protection laws and technical possibilities. To secure your data, we maintain technical and organizational security measures in accordance with Art. 32 GDPR, which we constantly adapt to the state of the art.
<br><br>
Your personal data will be transmitted encrypted with us. We use the Transport Layer Security (TLS) coding system, but would like to point out that data transmission over the Internet (e.g. when communicating by e-mail) can have security gaps. A complete protection of the data against access by third parties is therefore not guaranteed.
<br><br>
<b>13.Cookies</b>
<br>
Our website uses cookies and similar technologies. Cookies are text files that are stored in the internet browser or by the internet browser on the user's computer system. If a user calls up a website, a cookie can be stored on the user's operating system. Cookies contain a characteristic character string that can enable the browser to be clearly identified when the website is called up again. Similar technologies refer to other technical tools that enable the identification of website visitors, such as tracking pixels or LocalStorage.
<br><br>
Technically necessary cookies and technologies are those without which our website cannot function and be used. This category only includes cookies and technologies that ensure basic functionality and security features of the website. Technically necessary cookies and technologies can be set without the user's consent.
<br><br>
Non-necessary cookies are any cookies and technologies that may not be particularly necessary for the website to function and is used specifically to collect user personal data through tracking, ads, other embedded contents. Non-essential cookies and technologies (e.g. cookies for marketing, advertising or customer analysis purposes) require the consent of the website visitor.
<br><br>
By changing the settings in your Internet browser, you can deactivate or restrict the transmission of cookies. Cookies that have already been saved can be deleted at any time. This can also be done automatically. If cookies are deactivated for the website, it may no longer be possible to use all the functions of the website to their full extent.
<br><br>
We only use technically necessary cookies and technologies for our website. The "PHPSESSION" cookie is used to identify you when using our online services and is only saved during your session. We use LocalStorage to determine if you are logged in to our website.
<br><br>
<b>14. Changes to this Privacy Policy</b>
<br>
We reserve the right to change this privacy policy at any time in compliance with applicable laws and regulations.
<br><br>
The version available online at the time of your visit applies to the use of our online offer.
<br><br>
<i>Last modified: November 09, 2021..</i>

          </p>
        </div>

      </div>
    </section>

           <?php include('websiteNEWASSETS/includes/footer.php'); ?>

  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="websiteNEWASSETS/js/jquery-3.2.1.min.js"></script>
  <script src="websiteNEWASSETS/js/propper.js"></script>
  <script src="websiteNEWASSETS/js/bootstrap.min.js"></script>
  <script src="websiteNEWASSETS/vendors/wow/wow.min.js"></script>
  <script src="websiteNEWASSETS/vendors/sckroller/jquery.parallax-scroll.js"></script>
  <script src="websiteNEWASSETS/vendors/owl-carousel/owl.carousel.min.js"></script>
  <script src="websiteNEWASSETS/vendors/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="websiteNEWASSETS/vendors/isotope/isotope-min.js"></script>
  <script src="websiteNEWASSETS/vendors/magnify-pop/jquery.magnific-popup.min.js"></script>
  <script src="websiteNEWASSETS/vendors/scroll/jquery.mCustomScrollbar.concat.min.js"></script>
  <script src="websiteNEWASSETS/js/plugins.js"></script>
  <script src="websiteNEWASSETS/js/main.js"></script>
</body>

</html>
